from typing import List

def count_bases(sequence: str) -> List[int]:
    """
    Given a DNA sequence, return a list of the counts of each base.
    """
    counts = [0, 0, 0, 0]
    for base in sequence:
        if base == 'A':
            counts[0] += 1
        elif base == 'C':
            counts[1] += 1
        elif base == 'G':
            counts[2] += 1
        elif base == 'T':
            counts[3] += 1
    return " ".join([str(count) for count in counts])

bases = count_bases("ACATGTATATATGTTATTGGCAGCACGGCTCTTCGTCCGTTCAGTGGGTAATCGTATGCCATTGCCTTGATTTCAGCATCGACAGTTAACGTGTATCTCCTATAAAACGCGATAAGGAATGATTCGCGCGCGGCAGTATAATGTGGTCAGGTTCGCTTTTTCGGAACTGCGGCGGTGCGGCGGTCGGCAAGAGTAATACCGGCCGGAGTGGTTAGGATCGCTGCCGGACATTACGTCAGCGACAGGGTCCATATGCCATGATGCCTGTAACGTAATCAAGTTGGATCACTATATCTTCCAGCTAACCTAGCGATCCCGTAAACATGGCCCGAGGATTGAAGGAGCCATGAACACGTACGTGGGCTAAATACCGCTGCTCGTCCACCCTTATACTTACTGTTGTTCATCTCTCGCCCCTGGCCACGGATATTATTAGGGGGTTGGTGATAACGTAACAATGCGGTACGCAGGAACGAGATTAGCGGGCATGACCCGCCGCGATTAGGTGCGAGCCGAGCCCGGCAACTCCGAAGATTGAGGACAAGGCTATCGGTTCTCAACGGTAGAAGGGTGGCTGTCCAATCATGGTATCTTGCTATCAAATTAGAAAAGGTGACGCAAAAAACCCTGAAGCGATGCGCTGGCGAGTATTAAGAGGTCACGGTGATTCGATGCACCCGTGCTAGCCGCGGGGTTATCCCAACAGCGCCTTAAAGTCAGGCATGGACGTAAACAGACTCATGCGTGGAGCATTGCTATTAACTGCTTTTCAGTAGAGTTTAGCGCCAGGGGAAGATTTGACTACTCAAATAAACCACAGCTCACTGCCTCCCCCGTGCCCTCCGATCGTCA")

print(bases)